# Generated by Django 5.1 on 2024-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_wesitenewmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')])),
                ('department', models.IntegerField(choices=[(1, 'Physiotherapy'), (2, 'Physical Health'), (3, 'Treatments')])),
                ('date', models.DateField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
